# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# For more permissions see: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

name: Go

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        clean: false
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Setup
      run: |
        go install github.com/akavel/rsrc@latest
        go install mvdan.cc/garble@latest
    - name: Build syso
      run: rsrc -manifest uac.manifest -ico icon.ico -o uac.syso
    - name: Build exe
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 garble -tiny build
    - name: Run UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        version: latest
        files: |
          ./*.exe
        args: -fq --ultra-brute 
    - name: Clean old workflows
      uses: igorjs/gh-actions-clean-workflow@v3
      with:
        token: ${{ github.token }} # optional
        days_old: 1 # optional
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*.exe
        asset_name: InitVariables.exe
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
