# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# For more permissions see: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

name: Go

on:
  repository_dispatch:
  workflow_dispatch:

permissions: write-all

env:
  DELETE_OLD_WORKFLOW: true
  DELETE_USELESS_FILES: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize Build Space
      if: env.DELETE_USELESS_FILES == 'true' && !cancelled()
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 5120
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo timedatectl set-timezone "Asia/Shanghai"
        if [ "${{ env.DELETE_USELESS_FILES }}" == true ]
        then
            docker rmi $(docker images -q)
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
            sudo -E apt-get -y autoremove --purge
            sudo -E apt-get clean
        fi
    - uses: actions/checkout@v3
      with: 
        clean: false
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Setup
      run: |
        go install github.com/akavel/rsrc@latest
        go install mvdan.cc/garble@latest
    - name: Build syso
      run: rsrc -manifest uac.manifest -ico icon.ico -o uac.syso
    - name: Build exe
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 garble -tiny build
    - name: Run UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        version: latest
        files: |
          ./*.exe
        args: -fq --ultra-brute 
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*.exe
        asset_name: InitVariables.exe
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
        
    - name: Delete old Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      if: env.DELETE_OLD_WORKFLOW == 'true' && !cancelled()
      with:
        retain_days: 1
        keep_minimum_runs: 3
